services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - "6543:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
