services:
  postgres:
    image: postgres:17.2
    container_name: postgres-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - "6543:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -p 5432 -U user -d db" ]
      interval: 10s # Check every 10 seconds
      timeout: 5s # Timeout for each check
      retries: 5 # Retry up to 5 times before marking as unhealthy
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4:8.4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "9090:80" # Expose pgAdmin on port 9090
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
      - ./pgadmin4-config/servers.json:/pgadmin4/servers.json
    networks:
      - pg-network

networks:
  pg-network:
    driver: bridge
